const Privacy = () => (
  <div className="min-h-screen w-full flex items-center justify-center bg-gradient-to-br from-pink-100 via-orange-100 to-yellow-100 py-12 px-4">
    <div className="max-w-3xl w-full bg-white/90 rounded-3xl shadow-2xl p-8 md:p-12 border border-orange-200">
      <div className="flex flex-col items-center mb-8">
        {/* Playful icon/illustration */}
        <div className="mb-4 animate-bounce-gentle">
          <svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="32" cy="32" r="32" fill="url(#paint0_linear)"/>
            <ellipse cx="32" cy="40" rx="16" ry="8" fill="#FFF7E6"/>
            <ellipse cx="24" cy="28" rx="4" ry="6" fill="#FFB6B6"/>
            <ellipse cx="40" cy="28" rx="4" ry="6" fill="#FFB6B6"/>
            <ellipse cx="24" cy="28" rx="2" ry="3" fill="#fff"/>
            <ellipse cx="40" cy="28" rx="2" ry="3" fill="#fff"/>
            <ellipse cx="32" cy="38" rx="4" ry="2" fill="#FFB6B6"/>
            <defs>
              <linearGradient id="paint0_linear" x1="0" y1="0" x2="64" y2="64" gradientUnits="userSpaceOnUse">
                <stop stopColor="#FFB6B6"/>
                <stop offset="1" stopColor="#FFD580"/>
              </linearGradient>
            </defs>
          </svg>
        </div>
        <h1 className="text-4xl md:text-5xl font-kids font-bold text-orange-500 mb-2 text-center drop-shadow-lg">Privacy Policy</h1>
        <p className="text-lg text-muted-foreground text-center max-w-xl">This document is an electronic record under the Information Technology Act, 2000 and its rules, including amendments related to electronic records. This record is generated by a computerized system and does not require physical or digital signatures.</p>
      </div>
      <div className="prose prose-sm sm:prose lg:prose-lg max-w-none text-muted-foreground prose-h3:text-orange-600 prose-h3:font-bold prose-h3:mt-8 prose-h3:mb-2 prose-ul:pl-6 prose-li:marker:text-orange-400 prose-li:mb-1">
        <p>This Policy (“Policy”) is issued as per Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, for access or usage of Ozi.in or the “Ozi” Android/iOS app.</p>
        <h3>1. Who We Are</h3>
        <p>Ozi (operated by Ozi Technologies Private Limited, headquartered at Gurgaon, Haryana, India) owns and operates the careers.Ozi.club, life.Ozi.club, blog.Ozi.club websites, and the Ozi Android/iOS apps, collectively referred to as the “Website” or “App.”</p>
        <h3>2. Scope of This Policy</h3>
        <p>This Policy governs the collection, use, disclosure, and protection of information you provide when you access or use any Materials (products, services, features, content) on the Website or App.</p>
        <h3>3. Consent</h3>
        <p>By using our Website or App, you consent to the collection, use, disclosure, and retention of your personal information as described in this Policy.</p>
        <h3>4. Personal Information We Collect</h3>
        <ul>
          <li><strong>Account Data:</strong> name, email address, mobile number, shipping/billing address, date of birth.</li>
          <li><strong>Device & Usage Data:</strong> IP address, browser type, device model, operating system, app version, pages viewed, time spent, search queries, clickstreams.</li>
          <li><strong>Precise Location Data:</strong> optionally accessed via app if you grant permission (used for mapping and delivery).</li>
          <li><strong>Communications Data:</strong> messages or feedback submitted to our customer support, including attached files.</li>
          <li><strong>Marketing Engagement:</strong> data on how you interact with promotional messages and push notifications.</li>
        </ul>
        <h3>5. How We Use Your Personal Information</h3>
        <ul>
          <li>Provide, personalize, and improve products and services.</li>
          <li>Enable delivery via third-party logistics.</li>
          <li>Process and confirm orders, including refunds.</li>
          <li>Send promotional offers, updates, and communications.</li>
          <li>Respond to your requests, questions, or complaints.</li>
          <li>Analyze usage patterns for service enhancement.</li>
          <li>Ensure legal compliance and enforce our terms, policies, and fraud prevention.</li>
          <li>Share limited information with partners (e.g., warehouses, delivery providers) under confidentiality agreements.</li>
        </ul>
        <h3>6. Consent & Opt-In</h3>
        <p>By providing your personal data and using our services, you consent to its use for the purposes stated above. You may opt-out of marketing communications at any time via unsubscribe links, in-app settings, or by contacting us at contact@ozi.in.</p>
        <h3>7. Permissions & Data Use in the App</h3>
        <p>The app may request access to certain device permissions (e.g., location). These permissions are explicitly requested at run time, and you can decline or revoke them at any time.</p>
        <p><strong>Example:</strong></p>
        <ul>
          <li><strong>Allow Ozi to access your location?</strong></li>
          <li><strong>Purpose:</strong> Required for last-mile delivery coordination with logistics partners.</li>
        </ul>
        <h3>8. Sharing Personal Information</h3>
        <ul>
          <li><strong>Service Providers & Partners:</strong> logistics, payment processors, customer support, analytics, marketing firms.</li>
          <li><strong>Legal Authorities:</strong> when required by law or to enforce our policies.</li>
          <li><strong>Business Transfers:</strong> in cases of merger, acquisition, or asset sale—subject to confidentiality safeguards.</li>
        </ul>
        <p>We do not sell or rent your personal information.</p>
        <h3>9. Data Retention</h3>
        <p>We retain your personal data as long as:</p>
        <ul>
          <li>Necessary for service delivery (e.g., to complete transactions);</li>
          <li>Required by law (e.g., tax or accounting obligations);</li>
          <li>Reasonably needed to address disputes or enforce our policies.</li>
        </ul>
        <p>After this, data is securely deleted or anonymized.</p>
        <h3>10. Security Measures</h3>
        <p>We use reasonable technical and organizational controls (encryption, access restrictions, audits) to protect your data from unauthorized access, alteration, or loss. However, no system is entirely secure; we cannot guarantee absolute security.</p>
        <h3>11. Children’s Privacy</h3>
        <p>Our services are for users aged 18+. We do not knowingly collect data from minors. If we learn a minor’s data has been collected, we will delete it promptly upon verification.</p>
        <h3>12. Third-Party Links</h3>
        <p>Our services may link to external websites or services. This Policy applies only to Ozi. We are not responsible for the privacy practices or content of linked sites. We encourage you to review those independently.</p>
        <h3>13. Your Rights & Data Access</h3>
        <p>Subject to applicable laws, you have the right to:</p>
        <ul>
          <li>Access, correct, or update your data.</li>
          <li>Delete your account and personal information.</li>
          <li>Object to or restrict our processing.</li>
          <li>Export your data (data portability).</li>
          <li>Withdraw consent for processing (e.g., location, marketing) at any time.</li>
        </ul>
        <p>To exercise rights or update preferences, please contact us at contact@ozi.in.</p>
        <h3>14. Changes to This Policy</h3>
        <p>We may update this Policy periodically. The “Last Updated” date will reflect the change. Continued use after updates indicates acceptance. Please review regularly.</p>
        <h3>15. Contact Us</h3>
        <p>For inquiries, data requests, or complaints, email us at contact@ozi.in or write to:<br/>
        Ozi Technologies Private Limited<br/>
        [Your Street Address, Landmark]<br/>
        Gurgaon, Haryana, India</p>
        <p className="font-bold text-orange-500">Last Updated: July 15, 2025</p>
      </div>
    </div>
  </div>
);

export default Privacy; 